### PR TITLE
Update translations_fr.txt

### PR DESCRIPTION
**Pull request by arkfrance**

### CODE REVIEW

**Comment by LandDragoon** [comment]
Awesome work again. Can't thank you enough for this! :)

**Comment by arkfrance** [comment]
You welcome man, which software do you use to develop your app? 

Le 30 août 2016 00:17, LandDragoon notifications@github.com a écrit :

Awesome work again. Can't thank you enough for this! :)

**Comment by LandDragoon** [comment]
The app is made with React Native as that makes it a lot easier to distribute to both Android and iOS.

**Comment by arkfrance** [comment]
Ok, I wanted to make my app for Ark France but it seems to be complicated 

Le 30 août 2016 00:54, LandDragoon notifications@github.com a écrit :

The app is made with React Native as that makes it a lot easier to distribute to both Android and iOS.

**Comment by LandDragoon** [comment]
It depends on what you have in mind for an app. React Native makes use of Javascript, so you don't have to learn Java or Obj. C / Swift, making it a lot easier if you already know Javascript. For WordPress there is also an API available, so if you want to make an app that shows the post from your website then that would make it a lot easier to do. It will take some of time though, especially if you have never made an app before.

**Comment by arkfrance** [comment]
Yeah I want to do something like you with a left tab menu, for Xbox news, pc news, tutorials etc with the feeds of my website 

Cordialement 

Le 30 août 2016 10:28, LandDragoon notifications@github.com a écrit :

It depends on what you have in mind for an app. React Native makes use of Javascript, so you don't have to learn Java or Obj. C / Swift, making it a lot easier if you already know Javascript. For WordPress there is also an API available, so if you want to make an app that shows the post from your website then that would make it a lot easier to do. It will take some of time though, especially if you have never made an app before.

**Comment by LandDragoon** [comment]
For that you could take a look at the WordPress API: https://wordpress.org/plugins/rest-api/ to fetch the posts from your website and build an app around that. Another possibility is using your website's feed (arkfrancegaming.com/feed/) and see what you can use from there.

**Comment by arkfrance** [comment]
I'm trying to install everything to make the app on Mac, do I will have an interface to build the app? 

Le 30 août 2016 11:55, LandDragoon notifications@github.com a écrit :

For that you could take a look at the WordPress API: https://wordpress.org/plugins/rest-api/ to fetch the posts from your website and build an app around that. Another possibility is using your website's feed (arkfrancegaming.com/feed/) and see what you can use from there.

**Comment by LandDragoon** [comment]
I'll send you a mail ;p

**Pull request merged**
