### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by bertosbd**
Translated new literals and modified "tameo" by "doma". Tameo is not an spanish word. My username to include in collaborations is bertosbd

### CODE REVIEW

**Comment by LandDragoon** [comment]
Thanks a ton! You've added a lot of new translations :P Also thanks for changing the "tameo" word to the right one in ~~Italian~~ Spanish :) Is simply bertosbd enough or do you have a Twitter account or anything that you want to have linked too?

**Comment by bertosbd** [comment]
You're welcome! I love your app, keep doing this great work! I will try to finish translations to incorporate it on the next release, if you want. One question, this translations are in spanish ;-)


For the colaborations file, only bertosbd, i'm not joined in any social network...


Thx a lot!


Alberto

________________________________
De: LandDragoon <notifications@github.com>
Enviado: miércoles, 11 de enero de 2017 23:59
Para: SACompanion/translations
Cc: bertosbd; Author
Asunto: Re: [SACompanion/translations] Updated (#21)


Thanks a ton! You've added a lot of new translations :P Also thanks for changing the "tameo" word to the right one in Italian :) Is simply bertosbd enough or do you have a Twitter account or anything that you want to have linked too?

-

**Comment by LandDragoon** [comment]
Well, that's embarrassing :P For some reason I had Italian in my head and I have no idea why. Anyway, thanks for the **Spanish** translations and I'm looking forward to the rest :)

**Comment by bertosbd** [comment]
No problem :-D

Alberto
________________________________
De: LandDragoon <notifications@github.com>
Enviado: jueves, 12 de enero de 2017 14:07
Para: SACompanion/translations
Cc: bertosbd; Author
Asunto: Re: [SACompanion/translations] Updated (#21)


Well, that's embarrassing :P For some reason I had Italian in my head and I have no idea why. Anyway, thanks for the Spanish translations and I'm looking forward to the rest :)

-

**Pull request merged**
