### PR TITLE
Update translations_es.txt

### PR DESCRIPTION
**Pull request by bertosbd**
Added recipes translations.

Be carefull with this annotation:

en:  "ago",
es:  "hace", //on spanish ago is "hace", but this word goes before specified time. the example below is translated like 'Publicado hace 2 horas by Jat en Steam'
timePosted: "Posted {0} ago by {1} on {2}", //Example: Posted 2 hours ago by Jat on Steam.

Tomorrow I will try to finish it ;-D

### CODE REVIEW

**Comment by bertosbd** [comment]
All translated! :-D

**Comment by LandDragoon** [comment]
I can't thank you enough for this! Thanks a lot :) There might be an update of the translation files soon (as there are some new things added to the app that aren't in the current file yet). Would you also be able to translate some of those?

**Comment by bertosbd** [comment]
Sure! Count on it!

El 13 ene. 2017 11:53 p. m., LandDragoon <notifications@github.com> escribió:

I can't thank you enough for this! Thanks a lot :) There might be an update of the translation files soon (as there are some new things added to the app that aren't in the current file yet). Would you also be able to translate some of those?

**Comment by LandDragoon** [comment]
The file has been updated with new phrases and can be found [here](https://github.com/SACompanion/translations/blob/master/translations_es.txt). If you want to find the new phrases, the easiest way would be to search for "", (so 2 double quotes and comma), as untranslated text won't have any characters between the quotes yet.
If you run into any issues while translating, or if you are in doubts about the exact context of a phrase, let me know :)

**Comment by LandDragoon** [comment]
Hey, Any update on the translations? :)

**Comment by bertosbd** [comment]
Hi, sorry. I'm very busy this days. I will try to add new translations this week :-D

El 24 ene. 2017 11:17 a. m., LandDragoon <notifications@github.com> escribió:

Hey, Any update on the translations? :)

**Comment by bertosbd** [comment]
Hi again, all text translated with one exception (you can see it on pull request). Otherwise, I'm PS4 user, if you need some help about it, say me something!


De: LandDragoon <notifications@github.com>
Enviado: martes, 24 de enero de 2017 11:17
Para: SACompanion/translations
Cc: bertosbd; Author
Asunto: Re: [SACompanion/translations] Update translations_es.txt (#23)


Hey, Any update on the translations? :)

-

**Pull request merged**
